version: "3.8"
services:
  # Container: redis
  redis:
    image: redis
    container_name: cache
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - 6379
  # Container: discord bot
  bot:
    container_name: reservoir-discord-bot
    build: .
    depends_on:
      - redis
    links:
      - redis
    command: ["node", "./dist/index.js"]
    env_file:
      - .env
